### ISSUE TITLE
Users can create a new account.

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#1]
### Tasks

- [x]  Set up app on Heroku
- [x]  Set up Parse server
- [x]  Make registration view controller and add corresponding network calls
- [x] Add address field in registration
Optionally:
Find an external library for easier address entering/interpreting when it is stored
