### ISSUE TITLE
Users can mark follow-ups as completed or unable to complete

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#11]
### Description
Users can mark follow-ups in their follow-ups screen as complete or unable to complete in order to remove it from the follow ups

### Tasks
- [x] Create two buttons or drop-down options associated with each follow-up 
- [x] If follow-up was associated with user's own offer, make network call to remove the corresponding user from the respondees list
- [x] If follow-up was a request that user responded to, make network call to remove this post from the user's follow-ups array
- [x] Update table view upon completion of network request via delegates
