### ISSUE TITLE
Users can view their profile

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#12]
### Description
From the tab bar controller, users can view their own personal profile

### Tasks
- [x] Set up profile view controller
- [x] Populate with users' information
- [x] If not already done, add log out button to this view
