### ISSUE TITLE
Users can set their profile picture

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#13]
### Description
From their profile tab, users can click their profile image to change it

### Tasks
- [x] Set up image picker
- [x] Resize and upload chosen image to Parse
- [x] Refresh user's profile
- [x] Test from physical test device
- [x] Set up PFImageView to make setting images easier
- [x] Change editing permissions so other users cannot edit anyone's profile image
