### ISSUE TITLE
Users can respond to requests with a request for the user's information

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#14]
### Description
After implementing offer responses, I should have a better idea of what is feasible.

### Tasks
- [x] Add button to response details view, or alter existing button's response based on post type.
- [x] Create a new infoRequest
- [x] Allow the poster to view their info requests in a separate view associated with the Follow-Ups screen
- [x] Add approve and deny buttons for the poster to click associated with each info request they view
- [x] Upon approval, create a new follow-up
- [x] Upon denial, delete this info-request
