### ISSUE TITLE
Users can view other user's profiles

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#15]
### Description
Users should be able to click another user's username from the post feed, the post details view, and (optionally) the follow-up view to view their profile

### Tasks
- [x] Set up outsider perspective permissions on profile view
- [x] Implement username labels as buttons in the post feed and post details view
- [x] Upon button click, pass user information and segue to profile view
