### ISSUE TITLE
Users can view a map that marks places they have sent cards to or received cards

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#16]
### Description
Users can view a map that marks places they have sent cards to. This map does not mark places the user has received cards from, because the sending user's address is shared without consent in this way.

### Tasks
- [x] Create a view controller that user can get to from their profile
- [x] Integrate Apple mapkit
- [X] Create address model - includes refactoring existing code
- [x] Add a field to the User model that contains a list of their completed follow-ups
- [x] Grab list of users and their address from which to make coordinates
- [x] Drop a pin on the map for each place the user has sent cards
