### ISSUE TITLE
Users can filter posts by type.

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#17]
### Description
On their scroll feed, allow users to choose to filter their posts by offer or request only

### Tasks
- [x] Find new type of item for the UI to allow a button that triggers a drop down with selection
- [x] Adjust post query based on selection and reload
Optional:
- [x] Allow users to filter while searching (dependent upon search bar implementation)
- [x] Fixed many bugs associated with this
