### ISSUE TITLE
Add visual polish to the UI.

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#18]
### Description
Make the user interface more cool!

### Tasks

- [x] Stylize the fonts and colors
- - [x] Launch screen
- - [x] Login and registration screens
- - [x] Tab 1 screens
- - [x] Tab 2 screens
- - [x] Tab 3 screens
- [x] Add tab bar icons
- [x] Add for filter and compose
- [x] Adjust fonts and text sizes
- [x] Add animations
- - [x] fade in/out save and cancel buttons for about me

- [x] Add autolayout to the screens:
- - [x] Launch screen
- - [x] Login and registration screens
- - [x] Tab 1 screens
- - [x] Tab 2 screens
- - [x] Tab 3 screens
 - [x] Fix profile view header
- - [x] Figure out way to get the profile image selection working again
