### ISSUE TITLE
Make users unable to duplicate responses to posts

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#21]
### Description
Prevent users from being able to spam other users with post responses

## Tasks
- [X] Add condition for allowing users to send a response to a post
- [x] Visually change the response button upon first click
- [x] Display alert when user presses respond button to make sure they are sure
