### ISSUE TITLE
Refactor FollowUp data model 

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#23]
### Description 
Refactor the way I process Follow-Ups so that I do not rely on a User being logged in in order to create a new one - this creates issues with InfoRequests.

### Tasks
- [x] Create new Follow Up data model attached to Parse with fields for receivingUser, originalPost, and sendingUser
- [x] Detach Follow-Ups from User array
- [x] Query from all follow-ups instead of from a specific user
- [x] Every time someone responds to an offer or request, create a new follow up
- [x] Still need respondees for a post to eliminate double responses, but follow-ups will no longer need this field to "unwrap"
