### ISSUE TITLE
Users can infinitely scroll through posts

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#26]
### Description
More posts are loaded when a user reaches the end of the 20 posts.

### Tasks
- [x] Load in more posts when user reaches end of posts
- [x] Make sure this is compatible with searching and filtering
- [x] Refactor filtering to filter by querying instead
