### ISSUE TITLE
Users can have offers automatically close after a certain amount of responses.

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#28]
### Description
For example, the user can prevent responses to their offers after 20 responses are recorded.

### Tasks
- [X] Add  limit-setter in the compose process
- [x] Use the limit-setter to disable the response button and mark posts as completed after limit is met if post is an offer
- [x] Show number of responses on post cell only if post is an offer
- [x] Show number of responses in post details if post is an offer
- [x] Do not remove users from respondees list anymore
