### ISSUE TITLE
Users are notified when another user is unable to complete a request from you or an offer made by them.

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#29]
### Description
Users are notified when someone initially responds to their post. They are also notified if someone who responded marks the associated follow-up as "complete or "unable to complete". If thank-yous are implemented, they are also notified when they are tagged in a thank-you

### Tasks
- [ ] Create an activity view
- [ ] Add cells to the view with text depending on the action
- [ ] Allow user to dismiss the notification
