### ISSUE TITLE
Set up data models

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#3]
### Description
Set up data models based off data model property tables.

### Tasks
- [x] Set up User data model
- [x] Set up Post data model
- [x] Set up InfoRequest data model
- [x] Set up FollowUp data model
