### ISSUE TITLE
Implement auto-refreshing

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#31]
### Description
Auto-refresh posts for the user every so often

### Tasks
- [x] Create a timer
- [x] Set feed posts to refresh based on the timer
- [x] Also auto-refresh follow-ups 
- [x] Examine for any other places auto-refresh would be useful
