### ISSUE TITLE
Users can thank other users for received cards

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#33]
### Description
Either through a new kind of post or a button to thank the sending user

### Tasks
- [x] Make Thank You a third type of post
- [x] Disable respond buttons for thank-yous
- [x] Set up user tagging via Hakawai
- [x] Pull all tagged users into a list
- [x] Show thanked users in post details for thank you
- [x] Add thank you count to users' profiles
