### ISSUE TITLE
Users can mark region they are in/regions they are willing to send cards to

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#34]
### Description
When composing a new post, users can mark the region they are in (relevant for a request) or the region they are willing to send cards to (e.g Worldwide, USA only, Canada only, etc.)

### Tasks
- [ ] Add text fields (either user types manually, or can scroll through options) for marking region user is in and marking region user can send cards to
- [ ] Possibly allow user to configure the defaults for this in a settings page
- [ ] Prevent users who are in another region from responding to the post
