### ISSUE TITLE
Fix bugs

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#35]
### Description
General purpose card for bugs

### Tasks

- [x] If user switches their selected filter after searching a term, the selection does not update to search properly - could maybe be fixed in the future
- [x] Filtering, searching then pressing cancel shows incorrect filter
- [x] Follow-ups are duplicated by approving same inforequest multiple times
- [x] Move network calls outside of views
- [x] Profile View should be reconfigured to be just a tableview with sections, not scrollview then tableview probably
- [x] myPosts in profile view show in reverse order (should show newest first)
- [x] wrong person being added to sentTo users sometimes - had to do with the order of operations
- [x] Issue with transitioning from info request to associated post - author key is not including its keys. may need to add some duplicate fields back or else fetch in a way that makes sense
- [x] Fix tap gestures in follow up cells and info request cells only sending information from first cell. Issue is due to the segue marking the view controller itself as the sender instead of the cell.
