### ISSUE TITLE
Cap limits of inforequests and followups

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#37]
### Description
To prevent a backlog of too many follow-ups/info-requests, cap the limits of each

### Tasks
- [ ] If one user initiates an info-request to another user, show alert to requesting user and do not send a new info-request if the user has too many info-requests backed up - this one may be difficult without storing these in an array attached to the user
- [ ] If a user has too many follow-ups, prevent them from posting offers or responding to requests
- [ ] Visually display fullness of the follow-ups/info-requests
