### ISSUE TITLE
Users can login and logout

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#4]
### Tasks
- [x] Set up login view controller with login network call
- [x] Create alert upon failed login
- [x] Enable logout from profile view
