### ISSUE TITLE
Load profile image immediately upon changing it

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#42]
### Description
Instead of waiting for Parse to finish uploading the image, immediately change the profile image

### Tasks
- [x] Create delegate protocol for Profile View Controller
- [x] Assign ProfileHeaderCell as delegate by passing in the controller via the load method
- [x] Have the delegate set the image with the new image file
