### ISSUE TITLE
Users can make 2 kinds of posts: offers and requests

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#6]
### Descriptions
Users can compose either an offer or a request post, which is then stored in the Parse database

### Tasks
- [x] Set up compose view controller with appropriate labels for type, text fields, and buttons
- [x] Make network calls based on user actions
- [x] Bring user back to the home screen after posting
- [x] Prevent duplicate posts by disabling post button after 1 click
- [x] Posts on feed are updated immediately after posting via delegate method
