### ISSUE TITLE
Users can scroll through all posts

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#7]
### Description
Users can scroll through a feed of posts

### Tasks
- [x] Set up feed view controller with table view
- [x] Create a custom table view cell for posts
- [x] Query database for posts and populate cells
- [x] Add refresh control
