### ISSUE TITLE
Users can looks at the details of a post

### ISSUE THREAD

**Issue by Mer-cat** [Mer-cat/HappyMail#8]
### Description
Users can tap on a post from the scroll feed in order to view the full post.

### Tasks
- [x]  Set up details view screen
- [x]  Pass information from tapped cell during segue
- [x] Set up scroll view on details view
